plugins {
    id 'com.android.application'
}

android {
    namespace 'io.github.abdurazaaqmohammed.packs.network'
    compileSdk 36

    defaultConfig {
        applicationId 'io.github.abdurazaaqmohammed.packs.network'
        minSdk 19
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    compileOnly project(':sdk')
    compileOnly 'com.google.android.material:material:1.12.0'
    compileOnly 'androidx.appcompat:appcompat:1.7.0'
    compileOnly 'androidx.core:core:1.19.1'
    compileOnly 'com.google.zxing:core:3.5.3'
    compileOnly 'com.journeyapps:zxing-android-embedded:4.3.0'
}
