plugins {
    id 'com.android.application'
}

android {
    namespace 'io.github.abdurazaaqmohammed.packs.media'
    compileSdk 36

    defaultConfig {
        applicationId 'io.github.abdurazaaqmohammed.packs.media'
        minSdk 19
        versionCode 2
        versionName '1.1'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    compileOnly project(':sdk')
    compileOnly 'com.google.android.material:material:1.14.0'
    compileOnly 'androidx.appcompat:appcompat:1.7.0'
    compileOnly 'androidx.core:core:1.13.0'
}
