plugins {
    id 'com.android.library'
}

android {
    namespace 'io.github.abdurazaaqmohammed.sdk'
    compileSdk 36

    defaultConfig {
        minSdk 19
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'com.google.zxing:core:3.5.3'
}
